CREATE TYPE "training_category" AS ENUM (
	'code',
	'electronics',
	'robotic',
	'other',
	'software'
);

CREATE TYPE "roles" AS ENUM (
	'admin',
	'bureau',
	'cdp',
	'membre'
);

CREATE TYPE "permission" AS ENUM (
	'manage_training',
	'access_training'
);

CREATE TYPE "slot_status" AS ENUM (
	'draft',
	'pending',
	'done',
	'postponed',
	'canceled'
);

CREATE TYPE "registration_status" AS ENUM (
	'waitlisted',
	'registered',
	'canceled_by_user',
	'canceled_by_admin'
);


create table public.training (
  id bigint generated by default as identity not null,
  name text not null default ''::text,
  description text null,
  prerequisites text null,
  category public.training_category not null default 'other'::training_category,
  constraint training_pkey primary key (id)
) TABLESPACE pg_default;



create table public.training_slot (
  id bigint generated by default as identity not null,
  training_id bigint not null,
  custom_name text null,
  custom_description text null,
  custom_prerequisites text null,
  trainer_id uuid not null,
  start timestamp with time zone not null,
  duration_hours numeric not null,
  on_site_seats bigint null,
  remote_seats bigint null,
  location text null default ''::text,
  video_conference_link text null,
  excusable boolean not null,
  status public.slot_status not null default 'draft'::slot_status,
  constraint slot_pkey primary key (id),
  constraint slot_training_id_fkey foreign KEY (training_id) references training (id) on update CASCADE on delete set default,
  constraint slot_trainer_id_fkey foreign KEY (trainer_id) references profiles (id) on update CASCADE on delete RESTRICT,
  constraint training_slot_duration_hours_check check ((duration_hours > (0)::numeric)),
  constraint training_slot_on_site_seats_check check (
    (
      (on_site_seats is null)
      or ((on_site_seats)::numeric > (0)::numeric)
    )
  ),
  constraint training_slot_remote_seats_check check (
    (
      (remote_seats is null)
      or ((remote_seats)::numeric > (0)::numeric)
    )
  )
) TABLESPACE pg_default;




create table public.profiles (
  id uuid not null,
  role public.roles null,
  username text null default ''::text,
  avatar_url text null default 'https://avatar.iran.liara.run/public/boy'::text,
  permissions permission[] not null,
  constraint profiles_pkey primary key (id),
  constraint profiles_id_fkey foreign KEY (id) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.registration (
  slot_id bigint not null,
  member_id uuid not null,
  date_hour timestamp with time zone not null default (now() AT TIME ZONE 'utc+2'::text),
  remote boolean not null,
  status public.registration_status not null,
  present boolean null,
  to_excuse boolean null,
  feedback text null,
  constraint registration_pkey primary key (slot_id, member_id),
  constraint registration_slot_id_fkey foreign KEY (slot_id) references training_slot (id) on update CASCADE on delete CASCADE,
  constraint registration_member_id_fkey foreign KEY (member_id) references profiles (id) on update CASCADE on delete RESTRICT
) TABLESPACE pg_default;
